### PR TITLE
[Sample] Fix query orientation.

### LINKED ISSUE #30: com.android.mms and FileProvider
The target app com.android.mms crashes when an image is send as stream in the shared extras due to orientation check.

As the Uri has a content provider scheme, the com.android.mms skips the Exif check (which seems to be slow) and tries to query the MediaStore.Images.ImageColumns.ORIENTATION : 
http://androidxref.com/5.1.1_r6/xref/packages/apps/Mms/src/com/android/mms/ui/UriImage.java#546

Unfortunately, the default implementation of FileProvider from support-v4 won't return any data for such a query since only OpenableColumns.DISPLAY_NAME and OpenableColumns.SIZE are taken into account : 
http://androidxref.com/5.1.1_r6/xref/frameworks/support/v4/java/android/support/v4/content/FileProvider.java#421

As a result, http://androidxref.com/5.1.1_r6/xref/packages/apps/Mms/src/com/android/mms/ui/UriImage.java#546 will throw an exception.

FileProvider myst be extend in order to handle MediaStore.Images.ImageColumns.ORIENTATION query on our side.

### PR DESCRIPTION
**Pull request by vbarthel-fr**
The com.android.mms application is querying the FileProvider to get the orientation of the images.
The default implementation of FileProvider does not handle this query.
SharingFileProvider is a simple attempt at fixing this issue by returning the '0' as the orientation.

Should fix #30

### CODE REVIEW

File: sample/src/main/java/fr/tvbarthel/intentsharesample/SharingFileProvider.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    }
+
+    /**
+     * Query the {@link android.provider.MediaStore.Images.ImageColumns#ORIENTATION}
+     *
+     * @return Returns a {@link Cursor} with {@link android.provider.MediaStore.Images.ImageColumns#ORIENTATION} set to 180.
+     */
+    private Cursor queryMediaStoreOrientation() {
+        String[] cols = new String[]{MediaStore.Images.ImageColumns.ORIENTATION};
+        Object[] values = new Object[]{180};
```
Comment (tbarthel-fr) [inline sample/src/main/java/fr/tvbarthel/intentsharesample/SharingFileProvider.java]: Default rotation should be 0 degrees.

**Comment by vbarthel-fr** [comment]
I now use '0' as default orientation =)

**Comment by gabrielmaldi** [comment]
Just wanted to say **thank you** for discovering and fixing this!
